# GitHub Issue Templates

name: Bug Report
description: Report a bug in Poly State
title: '[Bug]: '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using a supported version
          required: true

  - type: input
    id: version
    attributes:
      label: Poly State Version
      description: What version of Poly State are you using?
      placeholder: '1.0.0'
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      options:
        - Vanilla TypeScript
        - React
        - Both
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: '18.17.0'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Create a store with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where does this bug occur?
      options:
        - Browser (Chrome/Chromium)
        - Browser (Firefox)
        - Browser (Safari)
        - Node.js
        - React Development
        - TypeScript Compilation
        - Build Process
        - Other (please specify in additional context)
    validations:
      required: true

  - type: checkboxes
    id: testing-env
    attributes:
      label: Testing Environment (for contributors)
      description: If you're contributing, which tests are failing?
      options:
        - label: Unit tests (jsdom environment)
          required: false
        - label: Browser tests (real Chromium)
          required: false
        - label: React integration tests
          required: false
        - label: Storage tests (localStorage, sessionStorage, cookies)
          required: false
        - label: Plugin system tests
          required: false
        - label: Build process
          required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code example that reproduces the issue
      render: typescript
      placeholder: |
        import { createStore } from 'poly-state';

        // Your code here
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, or context
      placeholder: Add any other context about the problem here...
    validations:
      required: false
